import { useState, useEffect, useCallback } from 'react';
import jsPDF from 'jspdf';

export interface TcmSession {
  id: string;
  startTime: string;
  endTime: string;
  duration: string;
  durationSeconds: number;
  questionsAsked: string[];
  conversationHistory: Array<{
    role: 'user' | 'assistant';
    content: string;
    timestamp: string;
  }>;
  totalQuestions: number;
  totalResponses: number;
  patientName?: string;
  patientEmail?: string;
  patientPhone?: string;
}

const STORAGE_KEY = 'tcm_session_history';
const MAX_SESSIONS = 50;

export function useTcmSessionHistory() {
  const [sessions, setSessions] = useState<TcmSession[]>([]);

  // Load sessions from localStorage on mount
  useEffect(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        setSessions(JSON.parse(saved));
      }
    } catch (e) {
      console.error('Failed to load session history:', e);
    }
  }, []);

  // Save session to localStorage
  const saveSession = useCallback((session: TcmSession) => {
    setSessions(prev => {
      const updated = [session, ...prev].slice(0, MAX_SESSIONS);
      try {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
      } catch (e) {
        console.error('Failed to save session:', e);
      }
      return updated;
    });
  }, []);

  // Delete a session
  const deleteSession = useCallback((sessionId: string) => {
    setSessions(prev => {
      const updated = prev.filter(s => s.id !== sessionId);
      try {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
      } catch (e) {
        console.error('Failed to delete session:', e);
      }
      return updated;
    });
  }, []);

  // Clear all sessions
  const clearAllSessions = useCallback(() => {
    setSessions([]);
    try {
      localStorage.removeItem(STORAGE_KEY);
    } catch (e) {
      console.error('Failed to clear sessions:', e);
    }
  }, []);

  // Generate PDF for a session
  const generateSessionPDF = useCallback((session: TcmSession): Blob => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let yPos = 20;

    // Header
    doc.setFontSize(20);
    doc.setTextColor(0, 128, 96); // Jade color
    doc.text('TCM Brain Session Report', pageWidth / 2, yPos, { align: 'center' });
    yPos += 15;

    // Session info
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Session ID: ${session.id}`, margin, yPos);
    yPos += 8;
    doc.text(`Date: ${new Date(session.startTime).toLocaleDateString()}`, margin, yPos);
    yPos += 8;
    doc.text(`Duration: ${session.duration}`, margin, yPos);
    yPos += 8;
    
    if (session.patientName) {
      doc.text(`Patient: ${session.patientName}`, margin, yPos);
      yPos += 8;
    }
    
    yPos += 5;
    doc.setDrawColor(0, 128, 96);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 10;

    // Questions Summary
    doc.setFontSize(14);
    doc.setTextColor(0, 128, 96);
    doc.text('Questions Asked', margin, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    session.questionsAsked.forEach((q, i) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      const lines = doc.splitTextToSize(`${i + 1}. ${q}`, pageWidth - margin * 2);
      doc.text(lines, margin, yPos);
      yPos += lines.length * 5 + 3;
    });

    yPos += 5;
    
    // Conversation History
    if (session.conversationHistory.length > 0) {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }
      
      doc.setFontSize(14);
      doc.setTextColor(0, 128, 96);
      doc.text('Conversation History', margin, yPos);
      yPos += 10;

      doc.setFontSize(9);
      session.conversationHistory.forEach(msg => {
        if (yPos > 260) {
          doc.addPage();
          yPos = 20;
        }
        
        const prefix = msg.role === 'user' ? 'Patient: ' : 'TCM Brain: ';
        doc.setTextColor(msg.role === 'user' ? 0 : 0, msg.role === 'user' ? 100 : 128, msg.role === 'user' ? 180 : 96);
        doc.setFont('helvetica', 'bold');
        doc.text(prefix, margin, yPos);
        
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);
        
        // Truncate long messages for PDF
        const truncatedContent = msg.content.length > 500 
          ? msg.content.substring(0, 500) + '...' 
          : msg.content;
        const lines = doc.splitTextToSize(truncatedContent, pageWidth - margin * 2 - 20);
        doc.text(lines, margin + 5, yPos + 5);
        yPos += lines.length * 4 + 10;
      });
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by TCM Brain - For professional use only', pageWidth / 2, 285, { align: 'center' });

    return doc.output('blob');
  }, []);

  // Export session as PDF file
  const exportSessionAsPDF = useCallback((session: TcmSession) => {
    const pdfBlob = generateSessionPDF(session);
    const url = URL.createObjectURL(pdfBlob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `tcm-session-${session.id}-${new Date(session.startTime).toISOString().split('T')[0]}.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [generateSessionPDF]);

  // Open Gmail with PDF attachment info
  const openGmailWithSession = useCallback((session: TcmSession, patientEmail?: string) => {
    const subject = encodeURIComponent(`TCM Brain Session Report - ${new Date(session.startTime).toLocaleDateString()}`);
    const body = encodeURIComponent(
      `Dear ${session.patientName || 'Patient'},\n\n` +
      `Please find attached your TCM Brain session report from ${new Date(session.startTime).toLocaleDateString()}.\n\n` +
      `Session Duration: ${session.duration}\n` +
      `Questions Discussed: ${session.totalQuestions}\n\n` +
      `Summary of Questions:\n${session.questionsAsked.map((q, i) => `${i + 1}. ${q}`).join('\n')}\n\n` +
      `Best regards,\nYour TCM Practitioner\n\n` +
      `Note: Please download the PDF report from the TCM Brain app and attach it to this email.`
    );
    
    const email = patientEmail || session.patientEmail || '';
    const gmailUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=${email}&su=${subject}&body=${body}`;
    
    window.open(gmailUrl, '_blank');
  }, []);

  // Open WhatsApp with session info
  const openWhatsAppWithSession = useCallback((session: TcmSession, patientPhone?: string) => {
    const phone = (patientPhone || session.patientPhone || '').replace(/\D/g, '');
    
    const message = encodeURIComponent(
      `🏥 *TCM Brain Session Report*\n\n` +
      `📅 Date: ${new Date(session.startTime).toLocaleDateString()}\n` +
      `⏱️ Duration: ${session.duration}\n` +
      `❓ Questions: ${session.totalQuestions}\n\n` +
      `*Questions Discussed:*\n${session.questionsAsked.slice(0, 5).map((q, i) => `${i + 1}. ${q}`).join('\n')}` +
      (session.questionsAsked.length > 5 ? `\n... and ${session.questionsAsked.length - 5} more` : '') +
      `\n\n_PDF report available upon request_`
    );
    
    const whatsappUrl = phone 
      ? `https://wa.me/${phone}?text=${message}`
      : `https://wa.me/?text=${message}`;
    
    window.open(whatsappUrl, '_blank');
  }, []);

  return {
    sessions,
    saveSession,
    deleteSession,
    clearAllSessions,
    generateSessionPDF,
    exportSessionAsPDF,
    openGmailWithSession,
    openWhatsAppWithSession
  };
}
